# Generated by Django 5.2.17 on 2026-09-27 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_identity', models.BigIntegerField(db_index=True, unique=True)),
                ('subscription_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('subscriber_type', models.CharField(blank=True, choices=[('FAHAM', 'faham'), ('NON_FAHAM', 'non_faham')], db_index=True, max_length=10, null=True)),
                ('tariff_digit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tariff_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('tariff_name', models.CharField(blank=True, max_length=255, null=True)),
                ('usage_group_code', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('usage_group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('usage_sub_group_code', models.CharField(blank=True, max_length=10, null=True)),
                ('usage_sub_group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('x_position', models.FloatField(blank=True, null=True)),
                ('y_position', models.FloatField(blank=True, null=True)),
                ('region_code', models.CharField(blank=True, max_length=10, null=True)),
                ('region_name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('branch_state_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('department_code', models.CharField(blank=True, max_length=10, null=True)),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_power', models.FloatField(blank=True, null=True)),
                ('phase_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('amper', models.FloatField(blank=True, null=True)),
                ('voltage', models.CharField(blank=True, max_length=50, null=True)),
                ('counter_type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('national_code', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('install_date_jalali', models.CharField(blank=True, max_length=10, null=True)),
                ('valid_to', models.CharField(blank=True, max_length=10, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('dl_insert_time', models.DateTimeField(auto_now_add=True)),
                ('dl_update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
            },
        ),
        migrations.CreateModel(
            name='CustomerChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date_jalali', models.CharField(max_length=10)),
                ('change_type_id', models.PositiveSmallIntegerField(choices=[(2, 'tariff code'), (3, 'counter serial number')])),
                ('change_type_name', models.CharField(max_length=100)),
                ('old_value', models.CharField(max_length=255)),
                ('new_value', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(db_column='bill_identity', on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='customers.customer', to_field='bill_identity')),
            ],
            options={
                'verbose_name': 'customer changelog',
                'verbose_name_plural': 'customer changelogs',
                'ordering': ['customer', 'change_date_jalali'],
                'indexes': [models.Index(fields=['customer', 'change_date_jalali'], name='customers_c_bill_id_2ff001_idx')],
            },
        ),
    ]
