# Generated by Django 5.2.17 on 2026-09-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='omor_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='omor_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
