# Generated by Django 5.2.17 on 2026-09-27 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('subscriber_type', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('subscription_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('start_date_jalali', models.CharField(max_length=10)),
                ('end_date_jalali', models.CharField(max_length=10)),
                ('cycle', models.CharField(db_index=True, max_length=6)),
                ('duration_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('low_kwh', models.FloatField(default=0)),
                ('medium_kwh', models.FloatField(default=0)),
                ('high_kwh', models.FloatField(default=0)),
                ('reactive_low_kwh', models.FloatField(default=0)),
                ('reactive_medium_kwh', models.FloatField(default=0)),
                ('reactive_high_kwh', models.FloatField(default=0)),
                ('friday_low_kwh', models.FloatField(default=0)),
                ('friday_medium_kwh', models.FloatField(default=0)),
                ('friday_high_kwh', models.FloatField(default=0)),
                ('read_power', models.FloatField(blank=True, null=True)),
                ('low_value', models.FloatField(default=0)),
                ('medium_value', models.FloatField(default=0)),
                ('high_value', models.FloatField(default=0)),
                ('debit_value', models.FloatField(default=0)),
                ('toll_value', models.FloatField(default=0)),
                ('canceled_date_jalali', models.CharField(blank=True, max_length=10, null=True)),
                ('emission_date_jalali', models.CharField(blank=True, max_length=10, null=True)),
                ('distribution_date_jalali', models.CharField(blank=True, max_length=10, null=True)),
                ('bill_type_id', models.PositiveSmallIntegerField(db_index=True)),
                ('bill_type_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tariff_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('tariff_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_update_time', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(db_column='bill_identity', on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='customers.customer', to_field='bill_identity')),
            ],
            options={
                'verbose_name': 'bill',
                'verbose_name_plural': 'bills',
                'ordering': ['customer', 'start_date_jalali'],
            },
        ),
        migrations.CreateModel(
            name='BillObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observe_id', models.PositiveSmallIntegerField()),
                ('observe_name', models.CharField(max_length=255)),
                ('observe_date_jalali', models.CharField(max_length=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='billing.bill')),
                ('customer', models.ForeignKey(db_column='bill_identity', on_delete=django.db.models.deletion.CASCADE, related_name='bill_observations', to='customers.customer', to_field='bill_identity')),
            ],
            options={
                'verbose_name': 'bill observation',
                'verbose_name_plural': 'bill observations',
            },
        ),
        migrations.CreateModel(
            name='MonthlyConsumptionEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_jalali', models.CharField(max_length=7)),
                ('days', models.PositiveSmallIntegerField()),
                ('low_kwh', models.FloatField(default=0)),
                ('medium_kwh', models.FloatField(default=0)),
                ('high_kwh', models.FloatField(default=0)),
                ('friday_low_kwh', models.FloatField(default=0)),
                ('friday_medium_kwh', models.FloatField(default=0)),
                ('friday_high_kwh', models.FloatField(default=0)),
                ('customer', models.ForeignKey(db_column='bill_identity', on_delete=django.db.models.deletion.CASCADE, related_name='monthly_estimates', to='customers.customer', to_field='bill_identity')),
            ],
            options={
                'verbose_name': 'monthly consumption estimate',
                'verbose_name_plural': 'monthly consumption estimates',
                'ordering': ['customer', 'period_jalali'],
                'constraints': [models.UniqueConstraint(fields=('customer', 'period_jalali'), name='uniq_customer_period')],
            },
        ),
    ]
