# Generated by Django 5.2.17 on 2026-09-27 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeteringStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.BigIntegerField(unique=True)),
                ('station_name', models.CharField(max_length=255)),
                ('station_type_id', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgds_code', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('meter_id', models.BigIntegerField(db_index=True, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=50)),
                ('tool_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('tool_name', models.CharField(blank=True, max_length=100)),
                ('tool_type_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('active_status', models.BooleanField(default=True)),
                ('formula_type_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('formula_mount_date', models.DateTimeField(blank=True, null=True)),
                ('formula_dismount_date', models.DateTimeField(blank=True, null=True)),
                ('ct_ratio', models.PositiveIntegerField(default=1)),
                ('pt_ratio', models.PositiveIntegerField(default=1)),
                ('mv_feeder_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('contract_power', models.FloatField(blank=True, null=True)),
                ('branch_state_code', models.CharField(blank=True, max_length=10, null=True)),
                ('branch_state_name', models.CharField(blank=True, max_length=255, null=True)),
                ('zone_name', models.CharField(blank=True, max_length=255, null=True)),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('remote_control_type', models.CharField(blank=True, max_length=100, null=True)),
                ('usage_type_id', models.CharField(blank=True, max_length=20, null=True)),
                ('customer', models.ForeignKey(blank=True, db_column='bill_identity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_tools', to='customers.customer', to_field='bill_identity')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='metering.meteringstation')),
            ],
        ),
        migrations.CreateModel(
            name='FeederCustomerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_customer_id', models.BigIntegerField(db_index=True)),
                ('last_update', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(db_column='bill_identity', on_delete=django.db.models.deletion.CASCADE, related_name='feeder_links', to='customers.customer', to_field='bill_identity')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_customers', to='metering.measurementtool')),
            ],
            options={
                'indexes': [models.Index(fields=['tool', 'is_deleted'], name='metering_fe_tool_id_68eb18_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'tool'), name='uniq_customer_tool_link')],
            },
        ),
        migrations.CreateModel(
            name='MeterQuarterlyEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_date', models.DateField()),
                ('sample_count', models.PositiveIntegerField()),
                ('first_time', models.DateTimeField()),
                ('last_time', models.DateTimeField()),
                ('sum_active_energy_export', models.FloatField(default=0)),
                ('sum_active_energy_import', models.FloatField(default=0)),
                ('sum_reactive_energy_export', models.FloatField(default=0)),
                ('sum_reactive_energy_import', models.FloatField(default=0)),
                ('avg_active_energy_export', models.FloatField(default=0)),
                ('max_active_energy_export', models.FloatField(default=0)),
                ('meter_count', models.PositiveIntegerField()),
                ('status_nonnull_count', models.PositiveIntegerField()),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_energy', to='metering.measurementtool')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tool', 'sample_date'), name='uniq_tool_quarter_day')],
            },
        ),
        migrations.CreateModel(
            name='SmartMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_tag', models.BigIntegerField(db_index=True)),
                ('reading_time', models.DateTimeField(db_index=True)),
                ('shamsi_date', models.CharField(blank=True, max_length=19, null=True)),
                ('meter_serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('power_active', models.FloatField(blank=True, null=True)),
                ('power_reactive', models.FloatField(blank=True, null=True)),
                ('power_factor', models.FloatField(blank=True, null=True)),
                ('demand', models.FloatField(blank=True, null=True)),
                ('frequency', models.FloatField(blank=True, null=True)),
                ('active_energy', models.FloatField(blank=True, null=True)),
                ('reactive_energy', models.FloatField(blank=True, null=True)),
                ('active_energy_export', models.FloatField(blank=True, null=True)),
                ('reactive_energy_export', models.FloatField(blank=True, null=True)),
                ('voltage_phase_a', models.FloatField(blank=True, null=True)),
                ('voltage_phase_b', models.FloatField(blank=True, null=True)),
                ('voltage_phase_c', models.FloatField(blank=True, null=True)),
                ('voltage_phase_n', models.FloatField(blank=True, null=True)),
                ('current_phase_a', models.FloatField(blank=True, null=True)),
                ('current_phase_b', models.FloatField(blank=True, null=True)),
                ('current_phase_c', models.FloatField(blank=True, null=True)),
                ('current_phase_n', models.FloatField(blank=True, null=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='metering.measurementtool')),
            ],
            options={
                'ordering': ['tool', 'reading_time'],
                'indexes': [models.Index(fields=['tool', 'reading_time'], name='metering_sm_tool_id_bb5522_idx')],
                'constraints': [models.UniqueConstraint(fields=('tool', 'time_tag'), name='uniq_tool_time_tag')],
            },
        ),
        migrations.CreateModel(
            name='ToolPowerDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_date', models.DateField()),
                ('sample_count', models.PositiveIntegerField()),
                ('first_time', models.DateTimeField()),
                ('last_time', models.DateTimeField()),
                ('avg_power', models.FloatField()),
                ('min_power', models.FloatField()),
                ('max_power', models.FloatField()),
                ('sum_power', models.FloatField()),
                ('active_status_count', models.PositiveIntegerField()),
                ('formula_type_count', models.PositiveIntegerField()),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_stats', to='metering.measurementtool')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tool', 'sample_date'), name='uniq_tool_power_day')],
            },
        ),
    ]
