# Generated by Django 5.2.17 on 2026-09-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementtool',
            name='billing_unit_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurementtool',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='measurementtool',
            name='customer_zone_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='measurementtool',
            name='customer_zone_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='measurementtool',
            name='department_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='measurementtool',
            name='faham_unit_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='measurementtool',
            name='identity_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='measurementtool',
            name='is_building',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurementtool',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='measurementtool',
            name='sub_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='measurementtool',
            name='subscription_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='measurementtool',
            name='unit_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurementtool',
            name='usage_group_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurementtool',
            name='usage_group_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='measurementtool',
            name='voltage_str',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='measurementtool',
            name='x_position',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurementtool',
            name='y_position',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurementtool',
            name='zone_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='smartmeterreading',
            name='current_l1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartmeterreading',
            name='current_l2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartmeterreading',
            name='current_l3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartmeterreading',
            name='dl_insert_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartmeterreading',
            name='guid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='smartmeterreading',
            name='phase_a_angle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartmeterreading',
            name='phase_b_angle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartmeterreading',
            name='phase_c_angle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartmeterreading',
            name='phase_n_angle',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartmeterreading',
            name='profile_status_energy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartmeterreading',
            name='profile_status_power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartmeterreading',
            name='source_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='smartmeterreading',
            name='source_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='smartmeterreading',
            name='voltage_l1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartmeterreading',
            name='voltage_l2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartmeterreading',
            name='voltage_l3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
