"""
Django settings for program project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a5n$u*b(_9@s3ldinxk(9bj#ykkx%23t&4+&37e)d&!)pyqp($'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

DATA_IMPORT_FILES = {
    'customers': BASE_DIR / 'assets' / 'chunk_customers.csv',
    'bills': BASE_DIR / 'assets' / 'chunk_bills.csv',
    'observes': BASE_DIR / 'assets' / 'chunk_observes.csv',
    'changes': BASE_DIR / 'assets' / 'chunk_changes.csv',
    'monthly': BASE_DIR / 'assets' / 'chunk_monthly.csv',
    'feeder_customers': BASE_DIR / 'assets' / 'subscribers.csv',
}

# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.customers',
    'apps.billing',
    'apps.metering',
    'apps.cli',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'program.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'program.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SQLite
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Postgres
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'anacav',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


UNFOLD = {
    'SITE_TITLE': 'Anacav Admin',
    'SITE_HEADER': 'Anacav',
    'SITE_SYMBOL': 'bolt',
    'SHOW_HISTORY': True,
    'SHOW_VIEW_ON_SITE': True,
    'SIDEBAR': {
        'show_search': True,
        'show_all_applications': False,
        'navigation': [
            {
                'title': 'Customers',
                'icon': 'people',
                'items': [
                    {
                        'title': 'Customers',
                        'icon': 'person',
                        'link': reverse_lazy('admin:customers_customer_changelist'),
                    },
                    {
                        'title': 'Change Logs',
                        'icon': 'history',
                        'link': reverse_lazy('admin:customers_customerchangelog_changelist'),
                    },
                ],
            },
            {
                'title': 'Billing',
                'icon': 'receipt_long',
                'items': [
                    {
                        'title': 'Bills',
                        'icon': 'receipt',
                        'link': reverse_lazy('admin:billing_bill_changelist'),
                    },
                    {
                        'title': 'Bill Observations',
                        'icon': 'visibility',
                        'link': reverse_lazy('admin:billing_billobservation_changelist'),
                    },
                    {
                        'title': 'Monthly Estimates',
                        'icon': 'calendar_month',
                        'link': reverse_lazy('admin:billing_monthlyconsumptionestimate_changelist'),
                    },
                ],
            },
            {
                'title': 'Metering',
                'icon': 'electric_meter',
                'items': [
                    {
                        'title': 'Metering Stations',
                        'icon': 'domain',
                        'link': reverse_lazy('admin:metering_meteringstation_changelist'),
                    },
                    {
                        'title': 'Measurement Tools',
                        'icon': 'speed',
                        'link': reverse_lazy('admin:metering_measurementtool_changelist'),
                    },
                    {
                        'title': 'Feeder Links',
                        'icon': 'account_tree',
                        'link': reverse_lazy('admin:metering_feedercustomerlink_changelist'),
                    },
                    {
                        'title': 'Power Daily Stats',
                        'icon': 'monitoring',
                        'link': reverse_lazy('admin:metering_toolpowerdailystat_changelist'),
                    },
                    {
                        'title': 'Quarterly Energy',
                        'icon': 'bar_chart',
                        'link': reverse_lazy('admin:metering_meterquarterlyenergy_changelist'),
                    },
                    {
                        'title': 'Smart Meter Readings',
                        'icon': 'query_stats',
                        'link': reverse_lazy('admin:metering_smartmeterreading_changelist'),
                    },
                ],
            },
            {
                'title': 'System',
                'icon': 'settings',
                'items': [
                    {
                        'title': 'Users',
                        'icon': 'people',
                        'link': reverse_lazy('admin:auth_user_changelist'),
                    },
                    {
                        'title': 'Groups',
                        'icon': 'group',
                        'link': reverse_lazy('admin:auth_group_changelist'),
                    },
                ],
            },
        ],
    },
}
